function s4c_gaze_stacked_bar(blocks)
%% Fraction of time gazing at each type of object in the environment -- 
% obstacles, terrain (ground), and other (e.g. mountains, border walls)
% NOTE: For all analyses in the paper, trials skipped by the subject were
% excluded
% NOTE: Error bars show standard error across subjects

clrs=def_colors; subjvec=[2,4,6,9,10,11,13,14,15,16,17,20,21];
gazeobs_premove=nan(5,13,60); gazeobs_nav=nan(5,13,60); 
gazeobs_search_byArena=nan(5,1); gazeobs_nav_byArena=nan(5,1); 
gazeterrain_search=nan(5,13,60); gazeterrain_nav=nan(5,13,60); 
gazeterrain_search_byArena=nan(5,1); gazeterrain_nav_byArena=nan(5,1);
gazeother_premove=nan(5,13,60); gazeother_move=nan(5,13,60);
gazeother_premove_byArena=nan(5,1); gazeother_move_byArena=nan(5,1);

%% Compute fraction of time
for arnum=1:5
    for subj=1:13
        subject=subjvec(subj); continuous=blocks{arnum}.continuous{subject};
        for trial=1:size(continuous,2)
            detected=blocks{arnum}.discrete{subject}(trial).detect_frame;
            
            gazeobs_premove(arnum,subject,trial)=sum(continuous{trial}.ObjTags(1:detected)==3 & ...
                ~isnan(continuous{trial}.gazeX_noblink(1:detected)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(1:detected)));
            gazeobs_nav(arnum,subject,trial)=sum(continuous{trial}.ObjTags(detected:end)==3 & ...
                ~isnan(continuous{trial}.gazeX_noblink(detected:end)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(detected:end)));
            
            gazeterrain_search(arnum,subject,trial)=sum(continuous{trial}.ObjTags(1:detected)==5 & ...
                ~isnan(continuous{trial}.gazeX_noblink(1:detected)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(1:detected)));
            gazeterrain_nav(arnum,subject,trial)=sum(continuous{trial}.ObjTags(detected:end)==5 & ...
                ~isnan(continuous{trial}.gazeX_noblink(detected:end)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(detected:end)));
            
            gazeobs_premove(arnum,subject,trial)=sum(continuous{trial}.ObjTags(1:detected)==3 & ...
                ~isnan(continuous{trial}.gazeX_noblink(1:detected)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(1:detected)));
            gazeobs_nav(arnum,subject,trial)=sum(continuous{trial}.ObjTags(detected:end)==3 & ...
                ~isnan(continuous{trial}.gazeX_noblink(detected:end)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(detected:end)));
            
            gazeother_premove(arnum,subject,trial)=sum(continuous{trial}.ObjTags(1:detected)~=3 & ...
                continuous{trial}.ObjTags(1:detected)~=5 & ...
                ~isnan(continuous{trial}.gazeX_noblink(1:detected)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(1:detected)));
            gazeother_move(arnum,subject,trial)=sum(continuous{trial}.ObjTags(detected:end)~=3 & ...
                continuous{trial}.ObjTags(detected:end)~=5 & ...
                ~isnan(continuous{trial}.gazeX_noblink(detected:end)))/...
                sum(~isnan(continuous{trial}.gazeX_noblink(detected:end)));
        end
    end
end

%% Take averages and normalize for each epoch
ind=exclude_skipped_trials(blocks);
gazeobs_premove(ind)=NaN; gazeobs_nav(ind)=NaN; gazeterrain_search(ind)=NaN; 
gazeterrain_nav(ind)=NaN; gazeother_premove(ind)=NaN; gazeother_move(ind)=NaN; 

for arnum=1:5
    gazeobs_search_byArena(arnum)=mean(gazeobs_premove(arnum,:,:),'all','omitnan')/...
        (mean(gazeobs_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeterrain_search(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    gazeobs_nav_byArena(arnum)=mean(gazeobs_nav(arnum,:,:),'all','omitnan')/...
        (mean(gazeobs_nav(arnum,:,:),'all','omitnan')+...
        mean(gazeterrain_nav(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan')); 
    gazeterrain_search_byArena(arnum)=mean(gazeterrain_search(arnum,:,:),'all','omitnan')/...
        (mean(gazeobs_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeterrain_search(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    gazeterrain_nav_byArena(arnum)=mean(gazeterrain_nav(arnum,:,:),'all','omitnan')/...
        (mean(gazeobs_nav(arnum,:,:),'all','omitnan')+...
        mean(gazeterrain_nav(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan')); 
    gazeother_premove_byArena(arnum)=mean(gazeother_premove(arnum,:,:),'all','omitnan')/...
        (mean(gazeobs_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeterrain_search(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    gazeother_move_byArena(arnum)=mean(gazeother_move(arnum,:,:),'all','omitnan')/...
        (mean(gazeobs_nav(arnum,:,:),'all','omitnan')+...
        mean(gazeterrain_nav(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan')); 
end

%% Plot
figure; hold on
b1=bar(0:4,flip([gazeobs_search_byArena,gazeterrain_search_byArena,...
    gazeother_premove_byArena]),'stacked','barwidth',1);
b2=bar(6:10,flip([gazeobs_nav_byArena,gazeterrain_nav_byArena,...
    gazeother_move_byArena]),'stacked','barwidth',1);
set(b1(1),'FaceColor',clrs.gold); set(b1(2),'FaceColor',clrs.green);
set(b1(3),'FaceColor',clrs.lilac); set(b2(1),'FaceColor',clrs.gold);
set(b2(2),'FaceColor',clrs.green); set(b2(3),'FaceColor',clrs.lilac); 

%% Format
movegui(gcf,'center')
set(gca,'color','w','fontsize',24,'Tickdir','out','Ticklength',[.03 .03],'xtick',[]); 
set(gcf,'color','w','InvertHardCopy','off')
ylim([0 1]); xlabel('   Search     Navigation'); ylabel('Fraction of time'); 
