function s8c_gaze_stacked_bar(blocks)
%% Fraction of time subjects exhibit each type of gaze (looking at target,
% looking at trajectory but not sweeping, sweeping the trajectory, and
% making other types of eye movements.
% NOTE: This analysis, like all eye movement analyses, exclude blinks from
% the total.
% NOTE: For all analyses in the paper, trials skipped by the subject were
% excluded
% NOTE: Error bars show standard error across subjects

clrs=def_colors; subjvec=[2,4,6,9,10,11,13,14,15,16,17,20,21];
gazetarg_premove=nan(5,13,60); gazetarg_move=nan(5,13,60); 
gazetarg_premove_byArena=nan(5,1); gazetarg_move_byArena=nan(5,1); 
gazetraj_premove=nan(5,13,60); gazetraj_move=nan(5,13,60); 
gazetraj_premove_byArena=nan(5,1); gazetraj_move_byArena=nan(5,1);
sweep_premove=nan(5,13,60); sweep_move=nan(5,13,60); 
sweep_premove_byArena=nan(5,1); sweep_move_byArena=nan(5,1);
gazeother_premove=nan(5,13,60); gazeother_move=nan(5,13,60);
gazeother_premove_byArena=nan(5,1); gazeother_move_byArena=nan(5,1);

%% Compute fraction of time
for arnum=1:5
    for subj=1:13
        subject=subjvec(subj); continuous=blocks{arnum}.continuous{subject};
        sweeps=blocks{arnum}.sweeps{subject};
        for trial=1:size(continuous,2)
            detected=blocks{arnum}.discrete{subject}(trial).detect_frame;
            start_move=blocks{arnum}.discrete{subject}(trial).start_move;
            stop_move=blocks{arnum}.discrete{subject}(trial).stop_move;
            gazeX=continuous{trial}.gazeX_noblink; gazeY=continuous{trial}.gazeY_noblink;
            % 1 = target, 2 = sweeping trajectory, 3 = trajectory but not
            % sweeping, 0 = other
            gaze_labels=zeros(length(continuous{trial}.trialTime),1);
            gaze_labels(continuous{trial}.idistfromtraj<2)=3;
            
            % What is labeled 3 but is actually occurring during a sweep
            % will now be labeled 2
            if ~isempty(sweeps{trial}.forward_sweeps)
                for sw=1:size(sweeps{trial}.forward_sweeps,1)
                    gaze_labels(sweeps{trial}.forward_sweeps(sw,1):...
                        sweeps{trial}.forward_sweeps(sw,2))=2;
                end
            end
            if ~isempty(sweeps{trial}.backward_sweeps)
                for sw=1:size(sweeps{trial}.backward_sweeps,1)
                    gaze_labels(sweeps{trial}.backward_sweeps(sw,1):...
                        sweeps{trial}.backward_sweeps(sw,2))=2;
                end
            end
            
            % What is labeled 3 or 2 but is actually the subject looking at
            % the target will now be labeled 1, and all else will remain 0.
            target=blocks{arnum}.discrete{subject}(trial).TargetStatenum+1;
            % Scale by 2 b/c the arena was scaled by 2 when loaded into Unity
            target_x=2*blocks{arnum}.arena.centroids(target,1);
            target_y=2*blocks{arnum}.arena.centroids(target,2);
            gaze_labels(sqrt((target_x-gazeX).^2+(target_y-gazeY).^2)<4*sqrt(3)/3)=1;
            gaze_labels(isnan(gazeX))=NaN;
            
            if ~isnan(start_move)
                gazetarg_premove(arnum,subj,trial)=sum(gaze_labels(detected:start_move)==1)/...
                    nnz(~isnan(gaze_labels(detected:start_move)));
                gazetraj_premove(arnum,subj,trial)=sum(gaze_labels(detected:start_move)==3)/...
                    nnz(~isnan(gaze_labels(detected:start_move)));
                sweep_premove(arnum,subj,trial)=sum(gaze_labels(detected:start_move)==2)/...
                    nnz(~isnan(gaze_labels(detected:start_move)));
                gazeother_premove(arnum,subj,trial)=sum(gaze_labels(detected:start_move)==0)/...
                    nnz(~isnan(gaze_labels(detected:start_move)));
                if ~isnan(stop_move)
                    gazetarg_move(arnum,subj,trial)=sum(gaze_labels(start_move:stop_move)==1)/...
                        nnz(~isnan(gaze_labels(start_move:stop_move)));
                    gazetraj_move(arnum,subj,trial)=sum(gaze_labels(start_move:stop_move)==3)/...
                        nnz(~isnan(gaze_labels(start_move:stop_move)));
                    sweep_move(arnum,subj,trial)=sum(gaze_labels(start_move:stop_move)==2)/...
                        nnz(~isnan(gaze_labels(start_move:stop_move)));
                    gazeother_move(arnum,subj,trial)=sum(gaze_labels(start_move:stop_move)==0)/...
                        nnz(~isnan(gaze_labels(start_move:stop_move)));
                else
                    gazetarg_move(arnum,subj,trial)=sum(gaze_labels(start_move:end)==1)/...
                        nnz(~isnan(gaze_labels(start_move:end)));
                    gazetraj_move(arnum,subj,trial)=sum(gaze_labels(start_move:end)==3)/...
                        nnz(~isnan(gaze_labels(start_move:end)));
                    sweep_move(arnum,subj,trial)=sum(gaze_labels(start_move:end)==2)/...
                        nnz(~isnan(gaze_labels(start_move:end)));
                    gazeother_move(arnum,subj,trial)=sum(gaze_labels(start_move:end)==0)/...
                        nnz(~isnan(gaze_labels(start_move:end)));
                end
            else
                gazetarg_premove(arnum,subj,trial)=sum(gaze_labels(detected:end)==1)/...
                    nnz(~isnan(gaze_labels(detected:end)));
                gazetraj_premove(arnum,subj,trial)=sum(gaze_labels(detected:end)==3)/...
                    nnz(~isnan(gaze_labels(detected:end)));
                sweep_premove(arnum,subj,trial)=sum(gaze_labels(detected:end)==2)/...
                    nnz(~isnan(gaze_labels(detected:end)));
                gazeother_premove(arnum,subj,trial)=sum(gaze_labels(detected:end)==0)/...
                    nnz(~isnan(gaze_labels(detected:end)));
            end
        end
    end
end

%% Take averages and normalize for each epoch
ind=exclude_skipped_trials(blocks);
gazetarg_premove(ind)=NaN; gazetarg_move(ind)=NaN; gazetraj_premove(ind)=NaN; 
gazetraj_move(ind)=NaN; gazeother_premove(ind)=NaN; gazeother_move(ind)=NaN; 

for arnum=1:5
    gazetarg_premove_byArena(arnum)=mean(gazetarg_premove(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_premove(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_premove(arnum,:,:),'all','omitnan')+...
        mean(sweep_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    gazetraj_premove_byArena(arnum)=mean(gazetraj_premove(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_premove(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_premove(arnum,:,:),'all','omitnan')+...
        mean(sweep_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    sweep_premove_byArena(arnum)=mean(sweep_premove(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_premove(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_premove(arnum,:,:),'all','omitnan')+...
        mean(sweep_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    gazeother_premove_byArena(arnum)=mean(gazeother_premove(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_premove(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_premove(arnum,:,:),'all','omitnan')+...
        mean(sweep_premove(arnum,:,:),'all','omitnan')+...
        mean(gazeother_premove(arnum,:,:),'all','omitnan'));
    gazetarg_move_byArena(arnum)=mean(gazetarg_move(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_move(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_move(arnum,:,:),'all','omitnan')+...
        mean(sweep_move(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan'));
    gazetraj_move_byArena(arnum)=mean(gazetraj_move(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_move(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_move(arnum,:,:),'all','omitnan')+...
        mean(sweep_move(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan'));
    sweep_move_byArena(arnum)=mean(sweep_move(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_move(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_move(arnum,:,:),'all','omitnan')+...
        mean(sweep_move(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan'));
    gazeother_move_byArena(arnum)=mean(gazeother_move(arnum,:,:),'all','omitnan')/...
        (mean(gazetarg_move(arnum,:,:),'all','omitnan')+...
        mean(gazetraj_move(arnum,:,:),'all','omitnan')+...
        mean(sweep_move(arnum,:,:),'all','omitnan')+...
        mean(gazeother_move(arnum,:,:),'all','omitnan'));
end

%% Plot
figure; hold on
b1=bar(0:4,flip([gazetarg_premove_byArena,sweep_premove_byArena,...
    gazetraj_premove_byArena,gazeother_premove_byArena]),'stacked','barwidth',1);
b2=bar(6:10,flip([gazetarg_move_byArena,sweep_move_byArena,...
    gazetraj_move_byArena,gazeother_move_byArena]),'stacked','barwidth',1);
set(b1(1),'FaceColor',clrs.green); set(b1(2),'FaceColor',clrs.purp2blue1);
set(b1(3),'FaceColor',clrs.lilac); set(b1(4),'FaceColor',clrs.lightgray);
set(b2(1),'FaceColor',clrs.green); set(b2(2),'FaceColor',clrs.purp2blue1);
set(b2(3),'FaceColor',clrs.lilac); set(b2(4),'FaceColor',clrs.lightgray);

%% Format
movegui(gcf,'center')
set(gca,'color','w','fontsize',24,'Tickdir','out','Ticklength',[.03 .03],'xtick',[]); 
set(gcf,'color','w','InvertHardCopy','off')
ylim([0 1]); xlabel(' Pre-movement   Movement'); ylabel('Fraction of time'); 
